### ISSUE TITLE
Reverse workflow

### ISSUE THREAD

**Issue by mcdoker18** [nokia/CloudFlow#34]
Hi.
Does CloudFlow support a reverse workflow? Or is it a bug?
Mistral: master (25 03 2018)
CloudFlow: 0.5.0

Workflow:
```yaml
version: '2.0'
test_r:
  type: reverse
  tasks:
    task0_1:
      action: std.sleep seconds=2
    task1_1:
      action: std.sleep seconds=2
      requires:
        - task0_1
    task1_2:
      action: std.sleep seconds=2
      requires:
        - task1_1
    task2_1:
      action: std.sleep seconds=2
      requires:
        - task0_1
    task2_2:
      action: std.sleep seconds=2
      requires:
        - task2_1
    task3_1:
      action: std.sleep seconds=2
      requires:
        - task2_2
        - task1_2
```
![screenshot from 2018-03-25 12-57-06](https://user-images.githubusercontent.com/6774206/37873348-3e14c862-302c-11e8-93be-ac28ad7943e4.png)
